package com.jogpal.app.features.run

import android.content.Context
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.graphics.Color as AndroidColor
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.viewmodel.compose.viewModel
import com.jogpal.app.core.designsystem.components.NeonMeshCard
import com.jogpal.app.data.run.RouteRepositoryImpl
import org.maplibre.android.camera.CameraUpdateFactory
import org.maplibre.android.geometry.LatLng
import org.maplibre.android.maps.MapView
import org.maplibre.android.maps.MapLibreMap
import org.maplibre.android.maps.Style
import org.maplibre.android.annotations.PolylineOptions
import org.maplibre.android.annotations.MarkerOptions
import kotlinx.coroutines.launch
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SoloActiveRunScreen(
    goalTypeName: String,
    goalValue: Double,
    routeShapeName: String,
    paceModeName: String,
    targetPace: Double,
    weatherName: String,
    themeName: String,
    ghostEnabled: Boolean,
    customStartLat: Double?,
    customStartLng: Double?,
    customEndLat: Double?,
    customEndLng: Double?,
    onNavigateBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val viewModel: ActiveRunViewModel = viewModel(factory = ActiveRunViewModelFactory(context))
    val uiState by viewModel.uiState.collectAsState()

    var isMapFollowing by remember { mutableStateOf(true) }
    var currentDeviceBearing by remember { mutableFloatStateOf(0f) }
    val goalType = remember { SoloGoalType.valueOf(goalTypeName) }

    var routePoints by remember { mutableStateOf<List<LatLng>>(emptyList()) }
    var routeGenerated by remember { mutableStateOf(false) }

    val scope = rememberCoroutineScope()
    val neonLime = Color(0xFFC8FF00)

    // Compass sensor logic
    DisposableEffect(Unit) {
        val sensorManager = context.getSystemService(Context.SENSOR_SERVICE) as SensorManager
        val rotationSensor = sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR)
        
        val sensorListener = object : SensorEventListener {
            override fun onSensorChanged(event: SensorEvent?) {
                if (event == null) return
                if (event.sensor.type == Sensor.TYPE_ROTATION_VECTOR) {
                    val rotationMatrix = FloatArray(9)
                    SensorManager.getRotationMatrixFromVector(rotationMatrix, event.values)
                    val orientationValues = FloatArray(3)
                    SensorManager.getOrientation(rotationMatrix, orientationValues)
                    val azimuth = Math.toDegrees(orientationValues[0].toDouble()).toFloat()
                    currentDeviceBearing = (azimuth + 360) % 360
                }
            }
            override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {}
        }
        
        rotationSensor?.let {
            sensorManager.registerListener(sensorListener, it, SensorManager.SENSOR_DELAY_UI)
        }
        onDispose {
            sensorManager.unregisterListener(sensorListener)
        }
    }

    LaunchedEffect(Unit) {
        viewModel.startTracking("SOLO_${System.currentTimeMillis()}")
        viewModel.resumeRun()
    }

    // Generate Route points
    val userLoc = uiState.userLocation
    LaunchedEffect(userLoc) {
        if (userLoc != null && !routeGenerated) {
            val startLat = customStartLat ?: userLoc.latitude
            val startLng = customStartLng ?: userLoc.longitude
            
            if (routeShapeName == "CUSTOM" && customEndLat != null && customEndLng != null) {
                scope.launch {
                    val repo = RouteRepositoryImpl()
                    repo.calculateRoute(startLat, startLng, customEndLat, customEndLng, false).fold(
                        onSuccess = { routes ->
                            if (routes.isNotEmpty()) {
                                routePoints = com.jogpal.app.core.common.PolylineUtils.decodePolyline(routes.first().encodedPolyline).toLatLngList()
                            }
                        },
                        onFailure = {}
                    )
                }
            } else {
                val dist = if (goalType == SoloGoalType.DISTANCE) goalValue else goalValue / targetPace
                routePoints = when (routeShapeName) {
                    "LOOP" -> com.jogpal.app.core.common.RouteLoopGenerator.generateLoop(startLat, startLng, dist)
                    "OUT_AND_BACK" -> com.jogpal.app.core.common.RouteLoopGenerator.generateOutAndBack(startLat, startLng, dist)
                    else -> com.jogpal.app.core.common.RouteLoopGenerator.generateRandomTrail(startLat, startLng, dist)
                }
            }
            routeGenerated = true
        }
    }

    // Ghost runner telemetry calculations
    val ghostDistance = remember(uiState.elapsedTimeSeconds, targetPace, ghostEnabled) {
        if (ghostEnabled && targetPace > 0) {
            (uiState.elapsedTimeSeconds / 60.0) / targetPace
        } else {
            0.0
        }
    }

    val ghostPosition = remember(ghostDistance, routePoints) {
        if (routePoints.isEmpty() || ghostDistance <= 0.0) {
            null
        } else {
            getPointAtDistance(routePoints, ghostDistance)
        }
    }

    // Map style JSON (Dark OSM style)
    val mapStyleUrl = remember(themeName) {
        """
        {
          "version": 8,
          "sources": {
            "osm": {
              "type": "raster",
              "tiles": ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
              "tileSize": 256,
              "attribution": "© OpenStreetMap contributors"
            }
          },
          "layers": [
            {
              "id": "osm",
              "type": "raster",
              "source": "osm",
              "minzoom": 0,
              "maxzoom": 19,
              "paint": {
                "raster-opacity": 0.85,
                "raster-brightness-max": 0.6,
                "raster-contrast": 0.35,
                "raster-saturation": -0.7
              }
            }
          ]
        }
        """.trimIndent()
    }

    var sosStatus by remember { mutableStateOf(com.jogpal.app.features.sos.SOSStatus.IDLE) }
    var showFinishConfirmationDialog by remember { mutableStateOf(false) }

    if (showFinishConfirmationDialog) {
        AlertDialog(
            onDismissRequest = { showFinishConfirmationDialog = false },
            title = { Text("Finish Solo Run?", fontWeight = FontWeight.Bold, color = Color.White) },
            text = { Text("Are you sure you want to end your run session now? Your progress will be saved.", color = Color.LightGray) },
            confirmButton = {
                Button(
                    onClick = {
                        showFinishConfirmationDialog = false
                        viewModel.finishRun()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = neonLime)
                ) {
                    Text("Finish Run", color = Color.Black, fontWeight = FontWeight.Bold)
                }
            },
            dismissButton = {
                TextButton(onClick = { showFinishConfirmationDialog = false }) {
                    Text("Cancel", color = Color.White)
                }
            },
            containerColor = Color(0xFF1E1E1E)
        )
    }

    if (uiState.finalSummary != null) {
        RunSummaryScreen(
            summary = uiState.finalSummary!!,
            onDone = onNavigateBack
        )
    } else {
        Scaffold(
            containerColor = Color.Black,
            topBar = {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .statusBarsPadding()
                        .padding(horizontal = 16.dp, vertical = 12.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    IconButton(
                        onClick = onNavigateBack,
                        modifier = Modifier
                            .size(42.dp)
                            .clip(CircleShape)
                            .background(Color(0xFF1E1E1E))
                    ) {
                        Icon(
                            imageVector = Icons.Default.ArrowBack,
                            contentDescription = "Back",
                            tint = Color.White
                        )
                    }

                    Spacer(modifier = Modifier.weight(1f))

                    Text(
                        text = "LIVE SOLO RUN",
                        fontSize = 18.sp,
                        fontWeight = FontWeight.ExtraBold,
                        color = Color.White,
                        letterSpacing = 2.sp
                    )

                    Spacer(modifier = Modifier.weight(1f))

                    com.jogpal.app.features.sos.components.SOSButton(
                        onClick = { sosStatus = com.jogpal.app.features.sos.SOSStatus.CONFIRMATION }
                    )
                }
            }
        ) { innerPadding ->
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(innerPadding)
                    .verticalScroll(rememberScrollState())
                    .padding(horizontal = 18.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // --- 1. TOP HEADER STATS CARD (Matching Screenshot 2) ---
                Card(
                    modifier = Modifier
                        .fillMaxWidth()
                        .border(1.5.dp, neonLime, RoundedCornerShape(26.dp)),
                    shape = RoundedCornerShape(26.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF0F1403))
                ) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 24.dp, vertical = 18.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        // Left Stat: DISTANCE
                        Column {
                            Text(
                                text = String.format(Locale.getDefault(), "%.2f", uiState.traveledDistanceKm),
                                fontSize = 36.sp,
                                fontWeight = FontWeight.Black,
                                color = neonLime
                            )
                            Text(
                                text = "DISTANCE",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White,
                                letterSpacing = 1.sp
                            )
                        }

                        // Right Stat: TIME
                        Column(horizontalAlignment = Alignment.End) {
                            val mins = (uiState.elapsedTimeSeconds % 3600) / 60
                            val secs = uiState.elapsedTimeSeconds % 60
                            Text(
                                text = String.format(Locale.getDefault(), "%02d:%02d", mins, secs),
                                fontSize = 36.sp,
                                fontWeight = FontWeight.Black,
                                color = neonLime
                            )
                            Text(
                                text = "TIME",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White,
                                letterSpacing = 1.sp
                            )
                        }
                    }
                }

                // --- 2. LIVE MAP VIEW CONTAINER ---
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(240.dp)
                        .clip(RoundedCornerShape(28.dp))
                        .background(Color(0xFF141414))
                ) {
                    var mapLibreMap by remember { mutableStateOf<MapLibreMap?>(null) }
                    val mapView = remember { MapView(context) }

                    val lifecycleOwner = androidx.lifecycle.compose.LocalLifecycleOwner.current
                    DisposableEffect(lifecycleOwner) {
                        val observer = androidx.lifecycle.LifecycleEventObserver { _, event ->
                            when (event) {
                                androidx.lifecycle.Lifecycle.Event.ON_START -> mapView.onStart()
                                androidx.lifecycle.Lifecycle.Event.ON_RESUME -> mapView.onResume()
                                androidx.lifecycle.Lifecycle.Event.ON_PAUSE -> mapView.onPause()
                                androidx.lifecycle.Lifecycle.Event.ON_STOP -> mapView.onStop()
                                androidx.lifecycle.Lifecycle.Event.ON_DESTROY -> mapView.onDestroy()
                                else -> {}
                            }
                        }
                        lifecycleOwner.lifecycle.addObserver(observer)
                        onDispose {
                            lifecycleOwner.lifecycle.removeObserver(observer)
                            mapView.onDestroy()
                        }
                    }

                    AndroidView(
                        factory = { mapView },
                        modifier = Modifier.fillMaxSize(),
                        update = { view ->
                            if (mapLibreMap == null) {
                                view.getMapAsync { map ->
                                    mapLibreMap = map
                                    map.setStyle(Style.Builder().fromJson(mapStyleUrl)) {
                                        val target = customStartLat?.let { LatLng(it, customStartLng ?: 0.0) }
                                            ?: userLoc?.let { LatLng(it.latitude, it.longitude) }
                                            ?: LatLng(0.0, 0.0)
                                        map.moveCamera(CameraUpdateFactory.newLatLngZoom(target, 16.5))
                                    }
                                    map.addOnCameraMoveStartedListener { reason ->
                                        if (reason == MapLibreMap.OnCameraMoveStartedListener.REASON_API_GESTURE) {
                                            isMapFollowing = false
                                        }
                                    }
                                }
                            }

                            val map = mapLibreMap ?: return@AndroidView
                            map.clear()

                            if (routePoints.isNotEmpty()) {
                                map.addPolyline(PolylineOptions()
                                    .addAll(routePoints)
                                    .color(AndroidColor.parseColor("#C8FF00"))
                                    .width(8f))
                                map.addMarker(MarkerOptions().position(routePoints.last()).title("FINISH LINE"))
                            }

                            ghostPosition?.let {
                                map.addMarker(MarkerOptions().position(it).title("GHOST PACER"))
                            }

                            userLoc?.let {
                                val point = LatLng(it.latitude, it.longitude)
                                map.addMarker(MarkerOptions().position(point).title("MY POSITION"))
                            }

                            if (isMapFollowing) {
                                val targetPoint = userLoc?.let { LatLng(it.latitude, it.longitude) }
                                    ?: customStartLat?.let { LatLng(it, customStartLng ?: 0.0) }
                                
                                targetPoint?.let { point ->
                                    val cameraUpdate = CameraUpdateFactory.newCameraPosition(
                                        org.maplibre.android.camera.CameraPosition.Builder()
                                            .target(point)
                                            .zoom(16.5)
                                            .bearing(currentDeviceBearing.toDouble())
                                            .tilt(35.0)
                                            .build()
                                    )
                                    map.animateCamera(cameraUpdate)
                                }
                            }
                        }
                    )

                    // Floating Compass Recenter Button
                    IconButton(
                        onClick = { isMapFollowing = true },
                        modifier = Modifier
                            .align(Alignment.BottomEnd)
                            .padding(14.dp)
                            .size(44.dp)
                            .clip(CircleShape)
                            .background(Color.Black.copy(alpha = 0.85f))
                    ) {
                        Icon(
                            imageVector = Icons.Default.Navigation,
                            contentDescription = "Center",
                            tint = neonLime
                        )
                    }
                }

                // --- 3. ROW OF 3 METRIC CARDS (Matching Screenshot 2) ---
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    // Card 1: DISTANCE
                    NeonMeshCard(
                        modifier = Modifier.weight(1f),
                        backgroundColor = Color(0xFF0F1403),
                        borderColor = neonLime,
                        borderWidth = 1.dp,
                        shape = RoundedCornerShape(22.dp)
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(vertical = 14.dp, horizontal = 10.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                text = String.format(Locale.getDefault(), "%.2f", uiState.traveledDistanceKm),
                                fontSize = 24.sp,
                                fontWeight = FontWeight.Black,
                                color = neonLime
                            )
                            Text(
                                text = "DISTANCE",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                        }
                    }

                    // Card 2: TIME
                    NeonMeshCard(
                        modifier = Modifier.weight(1f),
                        backgroundColor = Color(0xFF0F1403),
                        borderColor = neonLime,
                        borderWidth = 1.dp,
                        shape = RoundedCornerShape(22.dp)
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(vertical = 14.dp, horizontal = 10.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            val mins = (uiState.elapsedTimeSeconds % 3600) / 60
                            val secs = uiState.elapsedTimeSeconds % 60
                            Text(
                                text = String.format(Locale.getDefault(), "%02d:%02d", mins, secs),
                                fontSize = 24.sp,
                                fontWeight = FontWeight.Black,
                                color = neonLime
                            )
                            Text(
                                text = "TIME",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                        }
                    }

                    // Card 3: PACE /KM
                    NeonMeshCard(
                        modifier = Modifier.weight(1f),
                        backgroundColor = Color(0xFF0F1403),
                        borderColor = neonLime,
                        borderWidth = 1.dp,
                        shape = RoundedCornerShape(22.dp)
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(vertical = 14.dp, horizontal = 10.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                text = uiState.currentPace.ifBlank { "5:12" },
                                fontSize = 24.sp,
                                fontWeight = FontWeight.Black,
                                color = neonLime
                            )
                            Text(
                                text = "PACE /KM",
                                fontSize = 11.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                        }
                    }
                }

                // --- 4. MIDDLE TELEMETRY DASHBOARD (Matching Screenshot 2) ---
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    // Left Card: ELEVATION GAIN
                    Card(
                        modifier = Modifier
                            .weight(1f)
                            .height(130.dp),
                        shape = RoundedCornerShape(22.dp),
                        colors = CardDefaults.cardColors(containerColor = Color(0xFF141414))
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(14.dp),
                            verticalArrangement = Arrangement.SpaceBetween,
                            horizontalAlignment = Alignment.Start
                        ) {
                            Icon(
                                imageVector = Icons.Default.TrendingUp,
                                contentDescription = "Elevation",
                                tint = neonLime,
                                modifier = Modifier.size(24.dp)
                            )

                            Column {
                                Text(
                                    text = "ELEVATION GAIN:",
                                    fontSize = 10.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = Color.Gray
                                )
                                Text(
                                    text = "35M",
                                    fontSize = 20.sp,
                                    fontWeight = FontWeight.Black,
                                    color = Color.White
                                )
                            }
                        }
                    }

                    // Center Card: SEMI-CIRCULAR ARC GAUGE (TIME TO GOAL)
                    Card(
                        modifier = Modifier
                            .weight(1.2f)
                            .height(130.dp),
                        shape = RoundedCornerShape(22.dp),
                        colors = CardDefaults.cardColors(containerColor = Color(0xFF141414))
                    ) {
                        Box(
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(8.dp),
                            contentAlignment = Alignment.Center
                        ) {
                            val elapsedMins = (uiState.elapsedTimeSeconds / 60).toInt()
                            val targetMins = goalValue.toInt().coerceAtLeast(1)
                            val progress = (elapsedMins.toFloat() / targetMins).coerceIn(0f, 1f)

                            Canvas(modifier = Modifier.size(100.dp)) {
                                drawArc(
                                    color = Color(0xFF2A2A2A),
                                    startAngle = 140f,
                                    sweepAngle = 260f,
                                    useCenter = false,
                                    style = Stroke(width = 10.dp.toPx(), cap = StrokeCap.Round)
                                )
                                drawArc(
                                    color = neonLime,
                                    startAngle = 140f,
                                    sweepAngle = 260f * progress,
                                    useCenter = false,
                                    style = Stroke(width = 10.dp.toPx(), cap = StrokeCap.Round)
                                )
                            }

                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Text(
                                    text = String.format(Locale.getDefault(), "%d:00 / %d:00", elapsedMins, targetMins),
                                    fontSize = 12.sp,
                                    fontWeight = FontWeight.Black,
                                    color = neonLime
                                )
                                Text(
                                    text = "TIME TO GOAL",
                                    fontSize = 9.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = Color.Gray
                                )
                            }
                        }
                    }

                    // Right Card: AVERAGE PACE SPARKLINE
                    Card(
                        modifier = Modifier
                            .weight(1f)
                            .height(130.dp),
                        shape = RoundedCornerShape(22.dp),
                        colors = CardDefaults.cardColors(containerColor = Color(0xFF141414))
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxSize()
                                .padding(12.dp),
                            verticalArrangement = Arrangement.SpaceBetween
                        ) {
                            Canvas(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(40.dp)
                            ) {
                                val path = Path().apply {
                                    moveTo(0f, size.height * 0.7f)
                                    lineTo(size.width * 0.3f, size.height * 0.4f)
                                    lineTo(size.width * 0.6f, size.height * 0.6f)
                                    lineTo(size.width * 0.8f, size.height * 0.2f)
                                    lineTo(size.width, size.height * 0.3f)
                                }
                                drawPath(
                                    path = path,
                                    color = neonLime,
                                    style = Stroke(width = 3.dp.toPx(), cap = StrokeCap.Round)
                                )
                            }

                            Column {
                                Text(
                                    text = "AVERAGE PACE:",
                                    fontSize = 10.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = Color.Gray
                                )
                                Text(
                                    text = "5:21",
                                    fontSize = 20.sp,
                                    fontWeight = FontWeight.Black,
                                    color = Color.White
                                )
                            }
                        }
                    }
                }

                // (CREW PROGRESS section completely omitted per instruction)

                Spacer(modifier = Modifier.height(6.dp))

                // --- 5. BOTTOM ACTION BUTTONS (PAUSE / FINISH) ---
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(14.dp)
                ) {
                    // PAUSE / RESUME / START Pill Button
                    val isTracking = uiState.status == TrackingStatus.ACTIVE
                    val buttonLabel = when {
                        isTracking -> "PAUSE"
                        uiState.elapsedTimeSeconds == 0L -> "START"
                        else -> "RESUME"
                    }
                    
                    NeonMeshCard(
                        modifier = Modifier
                            .weight(1f)
                            .height(60.dp),
                        backgroundColor = if (isTracking) Color(0xFFFFD600) else neonLime,
                        shape = RoundedCornerShape(30.dp),
                        onClick = {
                            if (isTracking) viewModel.pauseRun() else viewModel.resumeRun()
                        }
                    ) {
                        Row(
                            modifier = Modifier.fillMaxSize(),
                            horizontalArrangement = Arrangement.Center,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = if (isTracking) Icons.Default.Pause else Icons.Default.PlayArrow,
                                contentDescription = buttonLabel,
                                tint = Color.Black,
                                modifier = Modifier.size(24.dp)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = buttonLabel,
                                fontSize = 16.sp,
                                fontWeight = FontWeight.Black,
                                color = Color.Black,
                                letterSpacing = 1.sp
                            )
                        }
                    }

                    // FINISH Flag Pill Button
                    NeonMeshCard(
                        modifier = Modifier
                            .weight(1f)
                            .height(60.dp),
                        backgroundColor = Color(0xFF1E3A00),
                        borderColor = neonLime,
                        borderWidth = 1.5.dp,
                        shape = RoundedCornerShape(30.dp),
                        onClick = { showFinishConfirmationDialog = true }
                    ) {
                        Row(
                            modifier = Modifier.fillMaxSize(),
                            horizontalArrangement = Arrangement.Center,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Icon(
                                imageVector = Icons.Default.Flag,
                                contentDescription = "Finish",
                                tint = neonLime,
                                modifier = Modifier.size(22.dp)
                            )
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                text = "FINISH",
                                fontSize = 16.sp,
                                fontWeight = FontWeight.Black,
                                color = neonLime,
                                letterSpacing = 1.sp
                            )
                        }
                    }
                }

                Spacer(modifier = Modifier.height(20.dp))
            }
        }
    }
}

// Helper function to find point along route
private fun getPointAtDistance(points: List<LatLng>, targetDistanceKm: Double): LatLng? {
    if (points.isEmpty()) return null
    var accumulatedKm = 0.0
    for (i in 0 until points.size - 1) {
        val p1 = points[i]
        val p2 = points[i + 1]
        val segDist = com.jogpal.app.core.common.LocationUtils.calculateDistanceKm(
            p1.latitude, p1.longitude, p2.latitude, p2.longitude
        )
        if (accumulatedKm + segDist >= targetDistanceKm) {
            val fraction = (targetDistanceKm - accumulatedKm) / segDist
            val lat = p1.latitude + fraction * (p2.latitude - p1.latitude)
            val lng = p1.longitude + fraction * (p2.longitude - p1.longitude)
            return LatLng(lat, lng)
        }
        accumulatedKm += segDist
    }
    return points.last()
}
