package com.jogpal.app.features.run

import android.content.Context
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.graphics.Color as AndroidColor
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Pause
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.viewmodel.compose.viewModel
import com.jogpal.app.core.common.LocationUtils
import com.jogpal.app.core.common.RouteLoopGenerator
import com.jogpal.app.core.designsystem.components.JogpalButton
import com.jogpal.app.data.run.RouteRepositoryImpl
import org.maplibre.android.camera.CameraUpdateFactory
import org.maplibre.android.geometry.LatLng
import org.maplibre.android.maps.MapView
import org.maplibre.android.maps.MapLibreMap
import org.maplibre.android.maps.Style
import org.maplibre.android.annotations.PolylineOptions
import org.maplibre.android.annotations.MarkerOptions
import kotlinx.coroutines.launch
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SoloActiveRunScreen(
    goalTypeName: String,
    goalValue: Double,
    routeShapeName: String,
    paceModeName: String,
    targetPace: Double,
    weatherName: String,
    themeName: String,
    ghostEnabled: Boolean,
    customStartLat: Double?,
    customStartLng: Double?,
    customEndLat: Double?,
    customEndLng: Double?,
    onNavigateBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val viewModel: ActiveRunViewModel = viewModel(factory = ActiveRunViewModelFactory(context))
    val uiState by viewModel.uiState.collectAsState()

    var isMapFollowing by remember { mutableStateOf(true) }
    var currentDeviceBearing by remember { mutableFloatStateOf(0f) }
    val goalType = remember { SoloGoalType.valueOf(goalTypeName) }

    var routePoints by remember { mutableStateOf<List<LatLng>>(emptyList()) }
    var routeGenerated by remember { mutableStateOf(false) }

    val scope = rememberCoroutineScope()

    // Compass sensor logic
    DisposableEffect(Unit) {
        val sensorManager = context.getSystemService(Context.SENSOR_SERVICE) as SensorManager
        val rotationSensor = sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR)
        
        val sensorListener = object : SensorEventListener {
            override fun onSensorChanged(event: SensorEvent?) {
                if (event == null) return
                if (event.sensor.type == Sensor.TYPE_ROTATION_VECTOR) {
                    val rotationMatrix = FloatArray(9)
                    SensorManager.getRotationMatrixFromVector(rotationMatrix, event.values)
                    val orientationValues = FloatArray(3)
                    SensorManager.getOrientation(rotationMatrix, orientationValues)
                    val azimuth = Math.toDegrees(orientationValues[0].toDouble()).toFloat()
                    currentDeviceBearing = (azimuth + 360) % 360
                }
            }
            override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {}
        }
        
        sensorManager.registerListener(sensorListener, rotationSensor, SensorManager.SENSOR_DELAY_UI)
        onDispose {
            sensorManager.unregisterListener(sensorListener)
        }
    }

    LaunchedEffect(Unit) {
        viewModel.startTracking("SOLO_${System.currentTimeMillis()}")
    }

    // Generate Route points
    val userLoc = uiState.userLocation
    LaunchedEffect(userLoc) {
        if (userLoc != null && !routeGenerated) {
            val startLat = customStartLat ?: userLoc.latitude
            val startLng = customStartLng ?: userLoc.longitude
            
            if (routeShapeName == "CUSTOM" && customEndLat != null && customEndLng != null) {
                scope.launch {
                    val repo = RouteRepositoryImpl()
                    repo.calculateRoute(startLat, startLng, customEndLat, customEndLng, false).fold(
                        onSuccess = { routes ->
                            if (routes.isNotEmpty()) {
                                routePoints = com.jogpal.app.core.common.PolylineUtils.decodePolyline(routes.first().encodedPolyline).toLatLngList()
                            }
                        },
                        onFailure = {}
                    )
                }
            } else {
                val dist = if (goalType == SoloGoalType.DISTANCE) goalValue else goalValue / targetPace
                routePoints = when (routeShapeName) {
                    "LOOP" -> RouteLoopGenerator.generateLoop(startLat, startLng, dist)
                    "OUT_AND_BACK" -> RouteLoopGenerator.generateOutAndBack(startLat, startLng, dist)
                    else -> RouteLoopGenerator.generateRandomTrail(startLat, startLng, dist)
                }
            }
            routeGenerated = true
        }
    }

    // Ghost runner telemetry calculations
    val ghostDistance = remember(uiState.elapsedTimeSeconds, targetPace, ghostEnabled) {
        if (ghostEnabled && targetPace > 0) {
            (uiState.elapsedTimeSeconds / 60.0) / targetPace
        } else {
            0.0
        }
    }

    val ghostPosition = remember(ghostDistance, routePoints) {
        if (routePoints.isEmpty() || ghostDistance <= 0.0) {
            null
        } else {
            getPointAtDistance(routePoints, ghostDistance)
        }
    }

    // Map style JSON (OSM base map styles)
    val mapStyleUrl = remember(themeName) {
        val tileUrl = if (themeName == "NIGHT") {
            "https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"
        } else {
            "https://a.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png"
        }
        """
        {
          "version": 8,
          "sources": {
            "osm": {
              "type": "raster",
              "tiles": ["$tileUrl"],
              "tileSize": 256,
              "attribution": "© CartoDB / © OpenStreetMap"
            }
          },
          "layers": [
            {
              "id": "osm",
              "type": "raster",
              "source": "osm",
              "minzoom": 0,
              "maxzoom": 20
            }
          ]
        }
        """.trimIndent()
    }

    if (uiState.finalSummary != null) {
        RunSummaryScreen(
            summary = uiState.finalSummary!!,
            onDone = onNavigateBack
        )
    } else {
        Scaffold(
            topBar = {
                CenterAlignedTopAppBar(
                    title = {
                        Column(horizontalAlignment = Alignment.CenterHorizontally) {
                            Text("SOLO ACTIVE RUN", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary, letterSpacing = 2.sp)
                            val goalDesc = when (goalType) {
                                SoloGoalType.FREE -> "Free Run"
                                SoloGoalType.DISTANCE -> String.format(Locale.getDefault(), "Goal: %.1f km", goalValue)
                                SoloGoalType.DURATION -> String.format(Locale.getDefault(), "Goal: %.0f min", goalValue)
                            }
                            Text(goalDesc, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.Transparent)
                )
            }
        ) { innerPadding ->
            Box(modifier = modifier.fillMaxSize().padding(innerPadding)) {
                // MAP View
                var mapLibreMap by remember { mutableStateOf<MapLibreMap?>(null) }
                val mapView = remember { MapView(context) }

                // Map Lifecycle
                val lifecycleOwner = androidx.lifecycle.compose.LocalLifecycleOwner.current
                DisposableEffect(lifecycleOwner) {
                    val observer = androidx.lifecycle.LifecycleEventObserver { _, event ->
                        when (event) {
                            androidx.lifecycle.Lifecycle.Event.ON_START -> mapView.onStart()
                            androidx.lifecycle.Lifecycle.Event.ON_RESUME -> mapView.onResume()
                            androidx.lifecycle.Lifecycle.Event.ON_PAUSE -> mapView.onPause()
                            androidx.lifecycle.Lifecycle.Event.ON_STOP -> mapView.onStop()
                            androidx.lifecycle.Lifecycle.Event.ON_DESTROY -> mapView.onDestroy()
                            else -> {}
                        }
                    }
                    lifecycleOwner.lifecycle.addObserver(observer)
                    onDispose {
                        lifecycleOwner.lifecycle.removeObserver(observer)
                        mapView.onDestroy()
                    }
                }

                AndroidView(
                    factory = { mapView },
                    modifier = Modifier.fillMaxSize(),
                    update = { view ->
                        if (mapLibreMap == null) {
                            view.getMapAsync { map ->
                                mapLibreMap = map
                                map.setStyle(Style.Builder().fromJson(mapStyleUrl)) {
                                    val target = customStartLat?.let { LatLng(it, customStartLng ?: 0.0) }
                                        ?: userLoc?.let { LatLng(it.latitude, it.longitude) }
                                        ?: LatLng(0.0, 0.0)
                                    map.moveCamera(CameraUpdateFactory.newLatLngZoom(target, 16.5))
                                }
                                map.addOnCameraMoveStartedListener { reason ->
                                    if (reason == MapLibreMap.OnCameraMoveStartedListener.REASON_API_GESTURE) {
                                        isMapFollowing = false
                                    }
                                }
                            }
                        }

                        val map = mapLibreMap ?: return@AndroidView
                        map.clear()

                        // Add generated route loop if present
                        if (routePoints.isNotEmpty()) {
                            map.addPolyline(PolylineOptions()
                                .addAll(routePoints)
                                .color(AndroidColor.parseColor("#3B82F6"))
                                .width(6f))
                            
                            // Finish Marker
                            map.addMarker(MarkerOptions().position(routePoints.last()).title("FINISH LINE"))
                        }

                        // Ghost Runner Marker
                        ghostPosition?.let {
                            map.addMarker(
                                MarkerOptions()
                                    .position(it)
                                    .title("GHOST PACER")
                            )
                        }

                        userLoc?.let {
                            val point = LatLng(it.latitude, it.longitude)
                            map.addMarker(MarkerOptions().position(point).title("MY POSITION"))
                            if (isMapFollowing) {
                                val cameraUpdate = CameraUpdateFactory.newCameraPosition(
                                    org.maplibre.android.camera.CameraPosition.Builder()
                                        .target(point)
                                        .zoom(16.5)
                                        .bearing(currentDeviceBearing.toDouble())
                                        .tilt(35.0)
                                        .build()
                                )
                                map.animateCamera(cameraUpdate)
                            }
                        }
                    }
                )

                // Weather overlay: Rain drops simulation
                if (weatherName == "RAINY") {
                    RainSimulationOverlay(modifier = Modifier.fillMaxSize())
                }

                // Goal Ring Gauge
                val progress = remember(uiState.traveledDistanceKm, uiState.elapsedTimeSeconds) {
                    when (goalType) {
                        SoloGoalType.FREE -> 0f
                        SoloGoalType.DISTANCE -> (uiState.traveledDistanceKm / goalValue).toFloat().coerceIn(0f, 1f)
                        SoloGoalType.DURATION -> ((uiState.elapsedTimeSeconds / 60.0) / goalValue).toFloat().coerceIn(0f, 1f)
                    }
                }

                if (goalType != SoloGoalType.FREE) {
                    Box(
                        modifier = Modifier
                            .align(Alignment.TopEnd)
                            .padding(16.dp)
                            .size(72.dp)
                            .clip(CircleShape)
                            .background(Color.White.copy(alpha = 0.9f)),
                        contentAlignment = Alignment.Center
                    ) {
                        val primaryColor = MaterialTheme.colorScheme.primary
                        Canvas(modifier = Modifier.size(54.dp)) {
                            drawCircle(
                                color = primaryColor.copy(alpha = 0.15f),
                                style = Stroke(width = 5.dp.toPx())
                            )
                            drawArc(
                                color = primaryColor,
                                startAngle = -90f,
                                sweepAngle = 360f * progress,
                                useCenter = false,
                                style = Stroke(width = 5.dp.toPx(), cap = StrokeCap.Round)
                            )
                        }
                        Text(
                            text = String.format(Locale.getDefault(), "%.0f%%", progress * 100),
                            fontWeight = FontWeight.Bold,
                            fontSize = 12.sp,
                            color = Color.Black
                        )
                    }
                }

                // Stats Dashboard (Airbnb/Uber Style Translucent Card)
                Card(
                    modifier = Modifier
                        .align(Alignment.BottomCenter)
                        .padding(20.dp)
                        .fillMaxWidth(),
                    shape = RoundedCornerShape(32.dp),
                    colors = CardDefaults.cardColors(containerColor = Color.White.copy(alpha = 0.9f)),
                    elevation = CardDefaults.cardElevation(12.dp)
                ) {
                    Column(modifier = Modifier.padding(24.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                        val hours = uiState.elapsedTimeSeconds / 3600
                        val minutes = (uiState.elapsedTimeSeconds % 3600) / 60
                        val seconds = uiState.elapsedTimeSeconds % 60
                        val timeStr = if (hours > 0) {
                            String.format(Locale.getDefault(), "%02d:%02d:%02d", hours, minutes, seconds)
                        } else {
                            String.format(Locale.getDefault(), "%02d:%02d", minutes, seconds)
                        }
                        
                        Text(text = timeStr, style = MaterialTheme.typography.displayMedium, fontWeight = FontWeight.Black, color = Color.Black)
                        Text(text = "DURATION", style = MaterialTheme.typography.labelSmall, color = Color.Gray)
                        
                        Spacer(modifier = Modifier.height(20.dp))
                        
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceEvenly) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("DISTANCE", style = MaterialTheme.typography.labelSmall, color = Color.Gray)
                                Text(String.format(Locale.getDefault(), "%.2f km", uiState.traveledDistanceKm), style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Black, color = Color.Black)
                            }
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("PACE", style = MaterialTheme.typography.labelSmall, color = Color.Gray)
                                Text(uiState.currentPace, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Black, color = Color.Black)
                            }
                        }

                        // Ghost difference stats
                        if (ghostEnabled) {
                            Spacer(modifier = Modifier.height(16.dp))
                            val diff = uiState.traveledDistanceKm - ghostDistance
                            val diffText = if (diff >= 0) {
                                String.format(Locale.getDefault(), "%.0f meters AHEAD of Virtual Partner", diff * 1000)
                            } else {
                                String.format(Locale.getDefault(), "%.0f meters BEHIND Virtual Partner", -diff * 1000)
                            }
                            Text(
                                text = diffText,
                                color = if (diff >= 0) MaterialTheme.colorScheme.primary else Color.Red,
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp
                            )
                        }
                        
                        Spacer(modifier = Modifier.height(28.dp))
                        
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                            if (uiState.status == TrackingStatus.ACTIVE) {
                                Box(modifier = Modifier.weight(1f)) {
                                    Button(
                                        onClick = { viewModel.pauseRun() },
                                        modifier = Modifier.fillMaxWidth().height(56.dp),
                                        shape = RoundedCornerShape(16.dp),
                                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFF3F4F6))
                                    ) {
                                        Icon(Icons.Default.Pause, contentDescription = "Pause", tint = Color.Black)
                                    }
                                }
                            } else {
                                Box(modifier = Modifier.weight(1f)) {
                                    Button(
                                        onClick = { viewModel.resumeRun() },
                                        modifier = Modifier.fillMaxWidth().height(56.dp),
                                        shape = RoundedCornerShape(16.dp),
                                        colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
                                    ) {
                                        Icon(Icons.Default.PlayArrow, contentDescription = "Resume", tint = Color.Black)
                                    }
                                }
                            }
                            
                            Box(modifier = Modifier.weight(1f)) {
                                JogpalButton(
                                    text = "Finish",
                                    onClick = { viewModel.finishRun() },
                                    containerColor = MaterialTheme.colorScheme.error
                                )
                            }
                        }
                    }
                }

                if (!isMapFollowing) {
                    Button(
                        onClick = { isMapFollowing = true },
                        modifier = Modifier.align(Alignment.TopStart).padding(16.dp),
                        shape = RoundedCornerShape(12.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = Color.White.copy(alpha = 0.9f), contentColor = Color.Black)
                    ) {
                        Text("Center Target", fontSize = 10.sp)
                    }
                }
            }
        }
    }
}

// Helpers
private fun getPointAtDistance(route: List<LatLng>, targetDistanceKm: Double): LatLng {
    if (route.isEmpty()) return LatLng(0.0, 0.0)
    if (targetDistanceKm <= 0.0) return route.first()
    
    var accumulated = 0.0
    for (i in 0 until route.size - 1) {
        val p1 = route[i]
        val p2 = route[i+1]
        val segmentDist = LocationUtils.calculateDistanceKm(p1.latitude, p1.longitude, p2.latitude, p2.longitude)
        if (accumulated + segmentDist >= targetDistanceKm) {
            val fraction = (targetDistanceKm - accumulated) / segmentDist
            val lat = p1.latitude + (p2.latitude - p1.latitude) * fraction
            val lng = p1.longitude + (p2.longitude - p1.longitude) * fraction
            return LatLng(lat, lng)
        }
        accumulated += segmentDist
    }
    return route.last()
}

@Composable
fun RainSimulationOverlay(modifier: Modifier = Modifier) {
    val infiniteTransition = rememberInfiniteTransition(label = "rain")
    val rainYOffset by infiniteTransition.animateFloat(
        initialValue = 0f,
        targetValue = 1000f,
        animationSpec = infiniteRepeatable(
            animation = tween(1200, easing = LinearEasing),
            repeatMode = RepeatMode.Restart
        ),
        label = "rainY"
    )

    val drops = remember {
        List(40) {
            Pair((0..1000).random().toFloat() / 1000f, (0..1000).random().toFloat() / 1000f)
        }
    }

    Canvas(modifier = modifier.fillMaxSize()) {
        val width = size.width
        val height = size.height
        drops.forEach { drop ->
            val startX = drop.first * width
            val startY = ((drop.second * height) + rainYOffset) % height
            drawLine(
                color = Color(0xFF60A5FA).copy(alpha = 0.25f),
                start = androidx.compose.ui.geometry.Offset(startX, startY),
                end = androidx.compose.ui.geometry.Offset(startX - 5f, startY + 25f),
                strokeWidth = 3f
            )
        }
    }
}
