package com.jogpal.app.features.run

import android.content.Context
import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.graphics.Color as AndroidColor
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Pause
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.lifecycle.viewmodel.compose.viewModel
import com.jogpal.app.core.common.RouteLoopGenerator
import com.jogpal.app.core.designsystem.components.JogpalButton
import org.maplibre.android.camera.CameraUpdateFactory
import org.maplibre.android.geometry.LatLng
import org.maplibre.android.maps.MapView
import org.maplibre.android.maps.MapLibreMap
import org.maplibre.android.maps.Style
import org.maplibre.android.annotations.PolylineOptions
import org.maplibre.android.annotations.MarkerOptions
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SoloActiveRunScreen(
    goalTypeName: String, // "FREE", "DISTANCE", "DURATION"
    goalValue: Double,
    onNavigateBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val viewModel: ActiveRunViewModel = viewModel(factory = ActiveRunViewModelFactory(context))
    val uiState by viewModel.uiState.collectAsState()

    var isMapFollowing by remember { mutableStateOf(true) }
    var currentDeviceBearing by remember { mutableFloatStateOf(0f) }
    val goalType = remember { SoloGoalType.valueOf(goalTypeName) }

    var loopRouteGenerated by remember { mutableStateOf(false) }
    var routePoints by remember { mutableStateOf<List<LatLng>>(emptyList()) }

    // GYRO / COMPASS sensor orientation logic
    DisposableEffect(Unit) {
        val sensorManager = context.getSystemService(Context.SENSOR_SERVICE) as SensorManager
        val rotationSensor = sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR)
        
        val sensorListener = object : SensorEventListener {
            override fun onSensorChanged(event: SensorEvent?) {
                if (event == null) return
                if (event.sensor.type == Sensor.TYPE_ROTATION_VECTOR) {
                    val rotationMatrix = FloatArray(9)
                    SensorManager.getRotationMatrixFromVector(rotationMatrix, event.values)
                    val orientationValues = FloatArray(3)
                    SensorManager.getOrientation(rotationMatrix, orientationValues)
                    // Convert azimuth to degrees
                    val azimuth = Math.toDegrees(orientationValues[0].toDouble()).toFloat()
                    currentDeviceBearing = (azimuth + 360) % 360
                }
            }
            override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {}
        }
        
        sensorManager.registerListener(sensorListener, rotationSensor, SensorManager.SENSOR_DELAY_UI)
        onDispose {
            sensorManager.unregisterListener(sensorListener)
        }
    }

    LaunchedEffect(Unit) {
        viewModel.startTracking("SOLO_${System.currentTimeMillis()}")
    }

    // Auto-generate loop route when user location becomes available
    val userLoc = uiState.userLocation
    LaunchedEffect(userLoc) {
        if (userLoc != null && goalType == SoloGoalType.DISTANCE && !loopRouteGenerated) {
            routePoints = RouteLoopGenerator.generateLoop(userLoc.latitude, userLoc.longitude, goalValue)
            loopRouteGenerated = true
        }
    }

    if (uiState.finalSummary != null) {
        RunSummaryScreen(
            summary = uiState.finalSummary!!,
            onDone = onNavigateBack
        )
    } else {
        Scaffold(
            topBar = {
                CenterAlignedTopAppBar(
                    title = {
                        Column(horizontalAlignment = Alignment.CenterHorizontally) {
                            Text("SOLO ACTIVE RUN", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary, letterSpacing = 2.sp)
                            val goalDesc = when (goalType) {
                                SoloGoalType.FREE -> "Free Run"
                                SoloGoalType.DISTANCE -> String.format(Locale.getDefault(), "Goal: %.1f km", goalValue)
                                SoloGoalType.DURATION -> String.format(Locale.getDefault(), "Goal: %.0f min", goalValue)
                            }
                            Text(goalDesc, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.Transparent)
                )
            }
        ) { innerPadding ->
            Box(modifier = modifier.fillMaxSize().padding(innerPadding)) {
                // MAP View
                var mapLibreMap by remember { mutableStateOf<MapLibreMap?>(null) }
                val mapView = remember { MapView(context) }

                val osmStyleJson = """
                {
                  "version": 8,
                  "sources": {
                    "osm": {
                      "type": "raster",
                      "tiles": ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
                      "tileSize": 256,
                      "attribution": "© OpenStreetMap contributors"
                    }
                  },
                  "layers": [
                    {
                      "id": "osm",
                      "type": "raster",
                      "source": "osm",
                      "minzoom": 0,
                      "maxzoom": 19
                    }
                  ]
                }
                """.trimIndent()

                // Map Lifecycle
                val lifecycleOwner = androidx.lifecycle.compose.LocalLifecycleOwner.current
                DisposableEffect(lifecycleOwner) {
                    val observer = androidx.lifecycle.LifecycleEventObserver { _, event ->
                        when (event) {
                            androidx.lifecycle.Lifecycle.Event.ON_START -> mapView.onStart()
                            androidx.lifecycle.Lifecycle.Event.ON_RESUME -> mapView.onResume()
                            androidx.lifecycle.Lifecycle.Event.ON_PAUSE -> mapView.onPause()
                            androidx.lifecycle.Lifecycle.Event.ON_STOP -> mapView.onStop()
                            androidx.lifecycle.Lifecycle.Event.ON_DESTROY -> mapView.onDestroy()
                            else -> {}
                        }
                    }
                    lifecycleOwner.lifecycle.addObserver(observer)
                    onDispose {
                        lifecycleOwner.lifecycle.removeObserver(observer)
                        mapView.onDestroy()
                    }
                }

                AndroidView(
                    factory = { mapView },
                    modifier = Modifier.fillMaxSize(),
                    update = { view ->
                        if (mapLibreMap == null) {
                            view.getMapAsync { map ->
                                mapLibreMap = map
                                map.setStyle(Style.Builder().fromJson(osmStyleJson)) {
                                    userLoc?.let {
                                        map.moveCamera(CameraUpdateFactory.newLatLngZoom(LatLng(it.latitude, it.longitude), 16.0))
                                    }
                                }
                                map.addOnCameraMoveStartedListener { reason ->
                                    if (reason == MapLibreMap.OnCameraMoveStartedListener.REASON_API_GESTURE) {
                                        isMapFollowing = false
                                    }
                                }
                            }
                        }

                        val map = mapLibreMap ?: return@AndroidView
                        map.clear()

                        // Add generated route loop if present
                        if (routePoints.isNotEmpty()) {
                            map.addPolyline(PolylineOptions()
                                .addAll(routePoints)
                                .color(AndroidColor.parseColor("#007AFF"))
                                .width(6f))
                            
                            // Finish Marker
                            map.addMarker(MarkerOptions().position(routePoints.last()).title("FINISH LINE"))
                        }

                        userLoc?.let {
                            val point = LatLng(it.latitude, it.longitude)
                            map.addMarker(MarkerOptions().position(point).title("MY POSITION"))
                            if (isMapFollowing) {
                                val cameraUpdate = CameraUpdateFactory.newCameraPosition(
                                    org.maplibre.android.camera.CameraPosition.Builder()
                                        .target(point)
                                        .zoom(16.5)
                                        .bearing(currentDeviceBearing.toDouble()) // Align camera with device compass/gyro
                                        .tilt(30.0) // Mild tilt for realistic first-person run perspective
                                        .build()
                                )
                                map.animateCamera(cameraUpdate)
                            }
                        }
                    }
                )

                // Goal Ring Gauge
                val progress = remember(uiState.traveledDistanceKm, uiState.elapsedTimeSeconds) {
                    when (goalType) {
                        SoloGoalType.FREE -> 0f
                        SoloGoalType.DISTANCE -> (uiState.traveledDistanceKm / goalValue).toFloat().coerceIn(0f, 1f)
                        SoloGoalType.DURATION -> ((uiState.elapsedTimeSeconds / 60.0) / goalValue).toFloat().coerceIn(0f, 1f)
                    }
                }

                if (goalType != SoloGoalType.FREE) {
                    Box(
                        modifier = Modifier
                            .align(Alignment.TopEnd)
                            .padding(16.dp)
                            .size(72.dp)
                            .clip(CircleShape)
                            .background(MaterialTheme.colorScheme.surface.copy(alpha = 0.9f)),
                        contentAlignment = Alignment.Center
                    ) {
                        val primaryColor = MaterialTheme.colorScheme.primary
                        Canvas(modifier = Modifier.size(54.dp)) {
                            drawCircle(
                                color = primaryColor.copy(alpha = 0.15f),
                                style = Stroke(width = 5.dp.toPx())
                            )
                            drawArc(
                                color = primaryColor,
                                startAngle = -90f,
                                sweepAngle = 360f * progress,
                                useCenter = false,
                                style = Stroke(width = 5.dp.toPx(), cap = StrokeCap.Round)
                            )
                        }
                        Text(
                            text = String.format(Locale.getDefault(), "%.0f%%", progress * 100),
                            fontWeight = FontWeight.Bold,
                            fontSize = 12.sp,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                    }
                }

                // Stats Dashboard
                Card(
                    modifier = Modifier
                        .align(Alignment.BottomCenter)
                        .padding(16.dp)
                        .fillMaxWidth(),
                    shape = RoundedCornerShape(32.dp),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.95f)),
                    elevation = CardDefaults.cardElevation(8.dp)
                ) {
                    Column(modifier = Modifier.padding(20.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                        val hours = uiState.elapsedTimeSeconds / 3600
                        val minutes = (uiState.elapsedTimeSeconds % 3600) / 60
                        val seconds = uiState.elapsedTimeSeconds % 60
                        val timeStr = if (hours > 0) {
                            String.format(Locale.getDefault(), "%02d:%02d:%02d", hours, minutes, seconds)
                        } else {
                            String.format(Locale.getDefault(), "%02d:%02d", minutes, seconds)
                        }
                        
                        Text(text = timeStr, style = MaterialTheme.typography.displayMedium, fontWeight = FontWeight.Black)
                        Text(text = "DURATION", style = MaterialTheme.typography.labelSmall, color = Color.Gray)
                        
                        Spacer(modifier = Modifier.height(24.dp))
                        
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceEvenly) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("DISTANCE", style = MaterialTheme.typography.labelSmall, color = Color.Gray)
                                Text(String.format(Locale.getDefault(), "%.2f km", uiState.traveledDistanceKm), style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Black)
                            }
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("PACE", style = MaterialTheme.typography.labelSmall, color = Color.Gray)
                                Text(uiState.currentPace, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Black)
                            }
                        }
                        
                        Spacer(modifier = Modifier.height(32.dp))
                        
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                            if (uiState.status == TrackingStatus.ACTIVE) {
                                Box(modifier = Modifier.weight(1f)) {
                                    Button(
                                        onClick = { viewModel.pauseRun() },
                                        modifier = Modifier.fillMaxWidth().height(56.dp),
                                        shape = RoundedCornerShape(16.dp),
                                        colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.secondaryContainer)
                                    ) {
                                        Icon(Icons.Default.Pause, contentDescription = "Pause", tint = MaterialTheme.colorScheme.onSecondaryContainer)
                                    }
                                }
                            } else {
                                Box(modifier = Modifier.weight(1f)) {
                                    Button(
                                        onClick = { viewModel.resumeRun() },
                                        modifier = Modifier.fillMaxWidth().height(56.dp),
                                        shape = RoundedCornerShape(16.dp),
                                        colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
                                    ) {
                                        Icon(Icons.Default.PlayArrow, contentDescription = "Resume", tint = Color.Black)
                                    }
                                }
                            }
                            
                            Box(modifier = Modifier.weight(1f)) {
                                JogpalButton(
                                    text = "Finish",
                                    onClick = { viewModel.finishRun() },
                                    containerColor = MaterialTheme.colorScheme.error
                                )
                            }
                        }
                    }
                }

                if (!isMapFollowing) {
                    Button(
                        onClick = { isMapFollowing = true },
                        modifier = Modifier.align(Alignment.TopStart).padding(16.dp),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Text("Center Target", fontSize = 10.sp)
                    }
                }
            }
        }
    }
}
